### ISSUE TITLE
Video is not playing in firefox web browser which is recorded by the chrome web browser in react

### ISSUE THREAD

**Issue by dayakarsreddy** [rico345100/react-multimedia-capture#3]
Video is not playing in firefox web browser which is recorded by the chrome web browser
1. We had recorded video in chrome browser and uploaded to server. Video is playing in chrome browser but not playing in firefox browser.
2. We had recorded video in firefox web browser and uploaded to server. Video is playing in firefox and chrome web browsers.
3. So we have a issue with playing videos in firefox which are recorded by the chrome browser.

Please let me know how can we fix it.

**Comment by rico345100** [comment]
Hello, did you try to play video manually in each browser by dragging to it? Was it worked?

react-multimedia-capture uses "video/webm;codecs=vp8" for video recording by default, and as I searched, latest builds of Chrome and FF support webm and VP8 both, so that couldn't be happened.

I want to test your case into my computer, but unfortunately I can't use video recorder now for some reason, so it could be little bit late to test, but I will notice you as possible as I can(AudioExample was worked).

I'm not sure why that happens, but seems like each browser has something different on recording media resources. Is there any warning or error message in console?  What about trying other MIME type instead and see it's work?

https://stackoverflow.com/questions/41739837/all-mime-types-supported-by-mediarecorder-in-firefox-and-chrome

**Comment by dayakarsreddy** [comment]
![screen shot 2018-02-15 at 3 27 52 pm](https://user-images.githubusercontent.com/11042451/36251227-75558002-1266-11e8-870b-5ee37fed29f3.png)

**Comment by dayakarsreddy** [comment]
![screen shot 2018-02-15 at 3 46 44 pm](https://user-images.githubusercontent.com/11042451/36251523-81d5c674-1267-11e8-8e85-4759b638d325.png)
![screen shot 2018-02-15 at 3 45 59 pm](https://user-images.githubusercontent.com/11042451/36251525-8221e694-1267-11e8-9238-a3f38759bc31.png)

**Comment by dayakarsreddy** [comment]
I have tried using different mime types but there is no luck.

**Comment by rico345100** [comment]
Hello, I just recorded video from Chrome and played to Firefox and it worked. I tested with [react-multimedia-capture-example](https://github.com/rico345100/react-multimedia-capture-example).

I don't know why that issue only happens to you. Anyway I keep try to find out how to solve your problem, but I think this isn't issue about react-multimedia-capture.

I think you should try recording video with HTML5 Media Device API and MediaRecorder API directly to see it's still not working. If it does, I couldn't help you.

**Comment by MarkBennett** [comment]
Hey! I know what's up! When I'm using Firefox I'm seeing errors about `event` not being defined in `index.js`.

<img width="623" alt="screen shot 2018-02-23 at 14 32 55" src="https://user-images.githubusercontent.com/61872/36617929-85fffa22-18a6-11e8-8473-16503da6766d.png">

These don't appear in Chrome. I looked into and this is because Chrome supports `Window.event`. This is a non-standard API from Internet Explorer days (surprise!) The actual name of the event argument in the callback handler used in this code is `ev`.

https://github.com/rico345100/react-multimedia-capture/blob/master/src/index.js#L118-L122

I've been able to verify that changing that lets me record in Firefox. I'm submitting a PR now!
