### ISSUE TITLE
Customization on start(handleStart) function

### ISSUE THREAD

**Issue by sravanshty** [rico345100/react-multimedia-capture#8]
Hello,

In MediaCapturer tag we have in-built functions like onGranted, onDenied, onStart, onStop, onPause.....for invoking these functions we are using like (<Button onClick={start}>Start</Button>).
 Now my query is like i wanted to invoke same start function but i just want to pass a value in Onclick, this is just because i just wanted to know that click fired from which button.
Could you please help me out.
Thanks in advance.

Thanks & Regards,
Sravan Kumar Shetty

**Comment by rico345100** [comment]
Why don't you just seperate handler for onstart and invoke manually when you needed?

**Comment by sravanshty** [comment]
Thanks for your reponse @rico345100 . Could you please give sample snippet because as i am new to react. Which would be helpfull to me.

Thanks & Regards,
Sravan Kumar Shetty

**Comment by sravanshty** [comment]
but to call this.handleStart directly where ever i required this function is accepting the stream as parameter to the function right. So if we call outside how do i pass stream. could you tell me.

**Comment by rico345100** [comment]
This place is talking about the issue which some sort of bug reporting or improvements, however your issue doesn't seems like both. If you have lack of knowledge about your programming skill, you can ask in [Stackoverflow](https://stackoverflow.com/).

I'm closing this because it's not an issue, however if you think this is an issue, you can freely re-open. Thanks.
